SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
PLAYER_RADIUS = 20
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

# Scoring
SCORE_LARGE_ASTEROID = 20  # kind=3, radius=60
SCORE_MEDIUM_ASTEROID = 50  # kind=2, radius=40
SCORE_SMALL_ASTEROID = 100  # kind=1, radius=20

# Lives system
STARTING_LIVES = 3
EXTRA_LIFE_POINTS = 10000

# Invincibility
INVINCIBILITY_DURATION = 2.5  # seconds
BLINK_INTERVAL = 0.1  # seconds between blinks
SAFETY_ZONE_RADIUS = 150  # pixels from center to clear asteroids

# UI
FONT_SIZE_LARGE = 72
FONT_SIZE_MEDIUM = 48
FONT_SIZE_SMALL = 32
HUD_MARGIN = 20
